server:
  port: 8761

spring:
  config:
    import:
      - classpath:/yaml/application-dev.yml
      - classpath:/yaml/application-prd.yml
  profiles:
    active: local
  application:
    name: wkEurekaDiscovery

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false