server:
  port: #{SERVER_PORT}

spring:
  application:
    name: wkEurekaDiscovery
  config:
    activate:
      on-profile: prd

eureka:
  client:
    register-with-eureka: false
    fetch-registry: false